sudo: false
language: erlang
otp_release:
  - 17.5
addons:
  apt:
    packages:
      - xsltproc
env:
  - BUILD_DIR=$HOME/rabbitmq-public-umbrella CONSUL_VERSION=0.5.2 RABBIT_TAG=rabbitmq_v3_5_6
install:
  - "$TRAVIS_BUILD_DIR/travis-umbrella-setup.sh"
  - "$TRAVIS_BUILD_DIR/travis-install-consul.sh"
script: cd $BUILD_DIR/autocluster && make test
before_deploy:
  - cd $BUILD_DIR/autocluster
  - VERSION=$TRAVIS_TAG make
  - mkdir -p $HOME/dpl
  - cd $HOME/dpl
cache:
  apt: true
  directories:
  - "$HOME/consul"
  - "$BUILD_DIR"
deploy:
  provider: releases
  api_key:
    secure: q4wUQ3KCg5Bi/JVC+yww017082G1Qa4n8Wwg9HH2K9Zwvx8ZtUeFOsWTU5s4FsYYroveW9ji98otuul3vyQikWcWf7neP3utRjd5LGjj13t89tUrU/pJU5HXgeLvy/u7ORCFVRVR3Lsk29MQ17IVQmO1PxbjwqYUiUMiY9D70LrDZmUCp1/4uCOVEbZEtmmuECn34gltwZ7dKBWTSomEX6VUDvNplu7RWVo3PkBk9oYepEC6ZAFxUvk9dVKMhbgY+QYpQ0BXxL4Z2N7CM7IHBr32imrC14Q6lpI0X1VMXtcZBuyskYbFdy83NqOJ1yzajtCPYVmFm4h9g0c4iefttzGvVuRREYyAIIRhtCdo7P7oVyBWzlxiFIOEnySrFIrX0Gu2OVhc954V5DrRnecUpy/9cr6q3gEolV6g4Oh059c/XmMIUfduKloYBCHgGMn1qfVdKKwX3iVjmVWyal5uYcKwtYmlW30QqkFNMPkRmT9DtegmXeS9ucT1rga0jAhgWxGWfY7hmhgf2Yk8pIGZWmHJ8/4tF8YfWPIzisj2Ch4edyhZiXJoTxZr2vOgBB+OUPW6vdxyal2TZypCI/JafMLSQUmOwrHcM3qhxSurPmYZbMJw8teXmohmQBvJpYIo+5elkcjMdGG6A3/VcdmGuHrHnEEFEZ3Z/UY+2moNh3Y=
  file: "$BUILD_DIR/autocluster/dist/autocluster-${TRAVIS_TAG}.ez"
  on:
    tags: true
    repo: revinate/rabbitmq-autocluster
